# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: Galacticum
markdown: redcarpet
pygments: true
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude

info: Galacticum is an infinite space game. Discover the universe and conquer planets!

navigation:
- text: Download
  title: News, Tutorials and more.
  url: /
- text: Progress
  title: Progress of the game
  url: /
- text: wiki
  title: Official galacticum wiki
  url: /

links:
- name: Impressum
  url: /
- name: dev blog
  url: /

